# Generated by Django 3.1.4 on 2020-12-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('createdAt', models.DateField(blank=True, default=None, null=True)),
                ('lastSeen', models.DateField(blank=True, default=None, null=True)),
                ('new', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
