# Generated by Django 3.1.4 on 2021-01-03 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(db_index=True, max_length=255)),
                ('store', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('url', models.CharField(db_index=True, max_length=255)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=7)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lastSeen', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('new', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='savedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('terms', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('source', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('price_min', models.CharField(blank=True, db_index=True, default=None, max_length=8, null=True)),
                ('price_max', models.CharField(blank=True, db_index=True, default=None, max_length=8, null=True)),
                ('sort', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('url', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('is_subscribed', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('hunter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
