# Generated by Django 3.1.4 on 2020-12-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='price',
        ),
    ]
