# Generated by Django 3.1.4 on 2020-12-30 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='store',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
