# Generated by Django 3.1.4 on 2021-01-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='new',
        ),
    ]
