# Generated by Django 3.1.4 on 2020-12-28 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201228_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='createdAt',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
