# Generated by Django 3.1.4 on 2020-12-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_camera_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='store',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
