# Generated by Django 3.1.4 on 2021-01-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_camera_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('success', models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
