# Generated by Django 3.1.4 on 2021-01-20 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_emailtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('iso', models.IntegerField(db_index=True)),
                ('type', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(db_index=True, max_length=255)),
                ('shipping', models.DecimalField(db_index=True, decimal_places=2, max_digits=7)),
                ('url', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='filmStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('url', models.CharField(db_index=True, max_length=255)),
                ('quantity', models.IntegerField(db_index=True)),
                ('film', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film', to='web.film')),
                ('source', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='web.source')),
            ],
        ),
        migrations.CreateModel(
            name='filmPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=7)),
                ('recordedAt', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stock', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='web.filmstock')),
            ],
            options={
                'ordering': ['-recordedAt'],
            },
        ),
    ]
