# Generated by Django 3.1.4 on 2020-12-30 15:13

from django.conf import settings
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_auto_20201229_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='savedSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', jsonfield.fields.JSONField()),
                ('hunter', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
