# Generated by Django 3.1.4 on 2020-12-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_camera_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['-createdAt']},
        ),
        migrations.AddField(
            model_name='camera',
            name='lastSeen',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='createdAt',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
