# Generated by Django 3.1.4 on 2020-12-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_savedsearch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='params',
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='new',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='price_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='sort',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
