# Generated by Django 3.1.4 on 2021-01-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_film_filmprice_filmstock_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='short_name',
            field=models.CharField(db_index=True, default='temp', max_length=255),
            preserve_default=False,
        ),
    ]
