# Generated by Django 3.1.4 on 2020-12-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_camera_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
