# Generated by Django 3.1.4 on 2020-12-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201230_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedsearch',
            name='hunter',
        ),
    ]
