# Generated by Django 3.1.4 on 2021-01-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_source_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='city',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='country',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='shipping',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='source',
            name='state',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255),
        ),
    ]
