# Generated by Django 3.1.4 on 2020-12-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_camera_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
