# Generated by Django 3.1.4 on 2020-12-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_savedsearch_hunter'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
