# Generated by Django 3.1.4 on 2020-12-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_savedsearch_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='price_max',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='price_min',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
