# Generated by Django 3.1.4 on 2020-12-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20201230_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='terms',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
