# Generated by Django 3.1.4 on 2020-12-30 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0010_savedsearch_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='hunter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='price_max',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='savedsearch',
            name='price_min',
            field=models.CharField(blank=True, default=None, max_length=8, null=True),
        ),
    ]
