# Generated by Django 3.1.4 on 2021-02-21 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_film_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmstock',
            name='film',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='web.film'),
        ),
    ]
