# Generated by Django 3.1.4 on 2021-02-21 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20210221_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmstock',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
