# Generated by Django 3.1.4 on 2020-12-30 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0011_auto_20201230_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='hunter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL),
        ),
    ]
