# Generated by Django 3.1.4 on 2021-02-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_film_exposures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmstock',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='web.source'),
        ),
    ]
