# Generated by Django 3.1.4 on 2021-02-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20210221_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='exposures',
            field=models.IntegerField(choices=[(36, '36'), (24, '24')], db_index=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='format',
            field=models.CharField(choices=[('35mm', '35mm'), ('120', '120')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='film',
            name='type',
            field=models.CharField(choices=[('bw', 'Black & white'), ('cn', 'Color negative'), ('cp', 'Color positive')], db_index=True, max_length=10),
        ),
    ]
