# Generated by Django 3.1.4 on 2021-02-27 19:31

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20210227_1151'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='film',
            managers=[
                ('lowest_price', django.db.models.manager.Manager()),
            ],
        ),
    ]
