# Generated by Django 3.1.4 on 2021-02-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20210227_1331'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='film',
            managers=[
            ],
        ),
    ]
