# Generated by Django 3.1.4 on 2021-02-27 21:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20210227_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmstock',
            options={'ordering': ['-price']},
        ),
        migrations.AlterModelManagers(
            name='film',
            managers=[
                ('price', django.db.models.manager.Manager()),
            ],
        ),
    ]
