# Generated by Django 3.1.4 on 2021-02-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20210227_1524'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='film',
            managers=[
            ],
        ),
    ]
