# Generated by Django 3.1.4 on 2021-02-28 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0022_film_lowupdatedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='followedFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_subscribed', models.BooleanField(db_index=True, default=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='web.film')),
                ('hunter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
