# Generated by Django 3.1.4 on 2021-02-28 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_followedfilm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followedfilm',
            name='film',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='web.film'),
        ),
    ]
