# Generated by Django 3.1.4 on 2021-02-28 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20210228_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmstock',
            name='lastSeen',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
