# Generated by Django 3.1.4 on 2021-03-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_auto_20210306_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='lowLast30d',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=7, null=True),
        ),
    ]
