# Generated by Django 3.1.4 on 2021-07-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_followedfilm_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='lastError',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
