# Generated by Django 3.1.4 on 2021-07-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_source_lasterror'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='lastError',
        ),
        migrations.AddField(
            model_name='source',
            name='lastScrapeTotal',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
