# Generated by Django 3.1.4 on 2021-07-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_auto_20210715_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
