# Generated by Django 3.1.4 on 2021-07-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_camera_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='url',
            field=models.URLField(db_index=True),
        ),
    ]
