# Generated by Django 3.1.4 on 2021-08-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_auto_20210723_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='experimental',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
