# Generated by Django 3.1.4 on 2021-08-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_film_experimental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followedfilm',
            name='in_stock',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
