# Generated by Django 3.1.4 on 2022-05-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_auto_20210818_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followedfilm',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='web.film'),
        ),
    ]
