# Generated by Django 3.1.4 on 2020-12-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('referral_code', models.CharField(blank=True, default=None, max_length=5, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
