# Generated by Django 3.1.4 on 2020-12-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunter',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
