# Generated by Django 3.1.4 on 2020-12-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunters', '0002_remove_hunter_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
