# Generated by Django 3.1.4 on 2020-12-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunters', '0003_hunter_searches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunter',
            name='searches',
        ),
    ]
