# Generated by Django 3.1.4 on 2021-01-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunters', '0003_auto_20201231_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunter',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='hunter',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
