# Generated by Django 3.1.4 on 2021-07-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunters', '0004_auto_20210108_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunter',
            name='stripe_customer_id',
            field=models.CharField(null=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='hunter',
            name='stripe_session_id',
            field=models.CharField(null=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='hunter',
            name='was_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
