# Generated by Django 3.1.4 on 2021-07-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunters', '0005_auto_20210713_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
