# Generated by Django 3.1.4 on 2021-07-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunters', '0006_auto_20210713_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunter',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hunter',
            name='stripe_session_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
